### PR TITLE
fix(branching_model): fix specific branch to main branch update

### LINKED ISSUE #104: `bitbucket_project_branching_model`: apply specific branch model to `use_mainbranch` results in panic
### Terraform Version
Terraform v1.3.5

### Affected Resource(s)
- bitbucket_project_branching_model

### Terraform Configuration Files
```hcl
resource "bitbucket_project_branching_model" "project_branching_model" {
  workspace = local.workspace.name
  project   = bitbucket_project.project.key

  development {
    use_mainbranch = true
  }
  production {
    use_mainbranch = true
    enabled        = true
  }
}
```

### Debug Output
```
  # bitbucket_project_branching_model.project_branching_model will be updated in-place
  ~ resource "bitbucket_project_branching_model" "project_branching_model" {
        id        = "<...>"
        # (2 unchanged attributes hidden)

      ~ development {
          - name                  = "a" -> null
          ~ use_mainbranch        = false -> true
            # (2 unchanged attributes hidden)
        }

      + production {
          + use_mainbranch = true
        }

        # (4 unchanged blocks hidden)
    }
```

### Panic Output
```
│ Error: API Error: 400 <..>/branching-model/settings Bad request
│ 
│   with bitbucket_project_branching_model.project_branching_model,
│   on main.tf line 44, in resource "bitbucket_project_branching_model" "project_branching_model":
│   44: resource "bitbucket_project_branching_model" "project_branching_model" {
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. Set your project branching model as follows manually through the Bitbucket UI

afbeelding

2. Set the HCL described in this issue
3. `terraform apply`

### PR DESCRIPTION
**Pull request by Nkmol**
This PR makes sure to reset the “specific branch” model type by setting the “name” to `null` when it is no longer defined.

Fixes #104

### CODE REVIEW

File: bitbucket/resource_branching_model.go [hunk 1]
```diff
@@ -21,11 +21,11 @@ type BranchingModel struct {
 }
 
 type BranchModel struct {
-	IsValid            bool   `json:"is_valid,omitempty"`
-	Name               string `json:"name,omitempty"`
-	UseMainbranch      bool   `json:"use_mainbranch,omitempty"`
-	BranchDoesNotExist bool   `json:"branch_does_not_exist,omitempty"`
-	Enabled            bool   `json:"enabled,omitempty"`
+	IsValid            bool    `json:"is_valid,omitempty"`
+	Name               *string `json:"name"`
```
Comment (Nkmol) [inline bitbucket/resource_branching_model.go:25]: Changing this to a pointer allows for nullable types, where removing `omitempty` makes sure the `nil` value is not omitted when marshalling.

File: bitbucket/resource_branching_model.go [hunk 2]
```diff
@@ -266,7 +266,11 @@ func expandBranchModel(l []interface{}) *BranchModel {
 	rp := &BranchModel{}
 
 	if v, ok := tfMap["name"].(string); ok {
-		rp.Name = v
+		if v == "" {
```
Comment (Nkmol) [inline bitbucket/resource_branching_model.go:269]: I was thinking to maybe use the raw value to actually differentiate between not set vs set as empty value (see https://github.com/hashicorp/terraform-plugin-sdk/issues/741). But I think this would sufice.
