### PR TITLE
Fix multiple bugs in handling of branch_types.enabled

### LINKED ISSUE #183: Attempting to disable the branch_types for the project never seems to get "fixed".
All the resources we're operating on have been imported as we am working on placing over 50 repos into an IaC setup simply because of the volume of manual changes and no-one knows who did what or necessarily where it is.

So, from that, there MAY be a 100 things we're not doing right simply due to the volume, but this is a slow and careful import and each step at the moment is to just confirm the resources are matching the live form and synchronizing things across the repos as we need to get that done.

The issue we're having is turning off the branch types (what I see as GitFlow branch name prefixes). None of the repos are used with GitFlow in mind and there's a mix of them being enabled / disabled amongst the repos. By disabling them at the project level (to start with) and see how far we get.

By having the following block in the `module.project.bitbucket_project_branching_model.branching_model` :
```hcl
  # GitFlow
  dynamic "branch_type" {
    for_each = ["bugfix", "feature", "hotfix", "release"]
    content {
      enabled = false
      kind    = branch_type.value
      prefix  = format("%s/", branch_type.value)
    }
  }
```
we get (as expected)
```
Terraform will perform the following actions:

  # module.project.bitbucket_project_branching_model.branching_model will be updated in-place
  ~ resource "bitbucket_project_branching_model" "branching_model" {
        id        = "digitickets/CID"
        # (2 unchanged attributes hidden)

      + branch_type {
          + enabled = false
          + kind    = "bugfix"
          + prefix  = "bugfix/"
        }
      + branch_type {
          + enabled = false
          + kind    = "feature"
          + prefix  = "feature/"
        }
      + branch_type {
          + enabled = false
          + kind    = "hotfix"
          + prefix  = "hotfix/"
        }
      + branch_type {
          + enabled = false
          + kind    = "release"
          + prefix  = "release/"
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

When we apply :
```
$  terraform apply "terraform.tfplan"
module.project.bitbucket_project_branching_model.branching_model: Modifying... [id=xxxx/CID]
module.project.bitbucket_project_branching_model.branching_model: Modifications complete after 2s [id=xxxx/CID]
```

All looks good so far!

Re-run the plan and the same outstanding change is required. Repeat this as often as you want and the same thing happens.

Tried replacing `false` with `null`, and with the `enabled` line removed, and the plan output is slightly different :
```
Terraform will perform the following actions:

  # module.project.bitbucket_project_branching_model.branching_model will be updated in-place
  ~ resource "bitbucket_project_branching_model" "branching_model" {
        id        = "digitickets/CID"
        # (2 unchanged attributes hidden)

      + branch_type {
          + enabled = (known after apply)
          + kind    = "bugfix"
          + prefix  = "bugfix/"
        }
      + branch_type {
          + enabled = (known after apply)
          + kind    = "feature"
          + prefix  = "feature/"
        }
      + branch_type {
          + enabled = (known after apply)
          + kind    = "hotfix"
          + prefix  = "hotfix/"
        }
      + branch_type {
          + enabled = (known after apply)
          + kind    = "release"
          + prefix  = "release/"
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

But the apply and replan shows that the change is still outstanding.

I also tried the fully expanded form, just in case that was the reason ... nope.

Plan always seems to want to change the bitbucket_project_branching_model.

Slightly behind on Terraform, and so null, false, handling ... maybe something there, but this is normally a provider issue.

```
### Terraform Version
$ terraform -v
Terraform v1.4.5
on darwin_amd64
+ provider registry.terraform.io/drfaust92/bitbucket v2.37.0
+ provider registry.terraform.io/hashicorp/aws v4.67.0
```

### Affected Resource(s)
- bitbucket_project_branching_model

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
Only update the resource if there is a difference to the branching model

### Actual Behavior
Every plan says the branch_types need "adding" with the `enabled` being set to `false` or `known after apply`.

### PR DESCRIPTION
**Pull request by barrywhart**
Fixes #183

### CODE REVIEW

File: bitbucket/resource_branching_model.go [hunk 1]
```diff
@@ -181,7 +184,7 @@ func resourceBranchingModelsRead(ctx context.Context, d *schema.ResourceData, m
 	if err != nil {
 		return diag.FromErr(err)
 	}
-	branchingModelsReq, _ := client.Get(fmt.Sprintf("2.0/repositories/%s/%s/branching-model", owner, repo))
+	branchingModelsReq, _ := client.Get(fmt.Sprintf("2.0/repositories/%s/%s/branching-model/settings", owner, repo))
```
Comment (barrywhart) [inline bitbucket/resource_branching_model.go:187]: The old code used the wrong API. The two APIs are similar, but the old one omits disabled branches in `branch_types`, and it omits `production` if disabled. Using `settings` returns everything. Note that the code was already using `settings` for `PUT` operations. This change aligns `GET` and `PUT` to use the same URL.

File: bitbucket/resource_branching_model.go [hunk 2]
```diff
@@ -206,6 +209,14 @@ func resourceBranchingModelsRead(ctx context.Context, d *schema.ResourceData, m
 		return diag.FromErr(decodeerr)
 	}
 
+	// Set default value for Enabled if it is nil
+	for _, branchType := range branchingModel.BranchTypes {
```
Comment (barrywhart) [inline bitbucket/resource_branching_model.go:213]: See the comment above (on `BranchType`) for an explanation of this code.

File: bitbucket/resource_branching_model.go [hunk 3]
```diff
@@ -302,11 +313,6 @@ func flattenBranchModel(rp *BranchModel, typ string) []interface{} {
 		"name":                  rp.Name,
 	}
 
-	// if production branch is disabled it wont show up in response and will show up without the proerty if enabled
```
Comment (barrywhart) [inline bitbucket/resource_branching_model.go:305]: This workaround should no longer be needed now that we're using the `settings` URL.
